import type { SiteLang } from "./locale";

const fr = {
  films: "Films & Séries",
  anime: "Animés",
  turkey: "Turquie",
  live: "TV Live",
  list: "Ma liste",
  search: "Recherche",
  account: "Compte & sécurité",
  switchProfile: "Changer de profil",
  logout: "Se déconnecter",
  searchFilm: "Un film ou une série",
  searchAnime: "Un animé",
  searchLive: "Une chaîne",
  searchTurkey: "Un film ou une série turque",
  searchHintTurkey: "Cherche un titre turc.",
  searchHintFilm: "Cherche un film ou une série.",
  searchHintAnime: "Cherche un animé.",
  searchHintLive: "Cherche une chaîne.",
  searching: "Recherche…",
  noResults: "Aucun résultat.",
  searchFailed: "Recherche impossible. Réessaie.",
  opening: "Ouverture…",
  notPlayable: "Pas encore disponible à la lecture",
  actors: "Acteurs",
  titles: "titres",
  movie: "FILM",
  show: "SÉRIE",
  play: "Lecture",
  playUnavailable: "Lecture indisponible",
  episodes: "Épisodes",
  close: "Fermer",
  sheetUnavailable: "Fiche indisponible",
  seasonUnavailable: "Saison introuvable",
  episode: "Épisode",
  playbackFailed: "Lecture impossible",
  channelDown: "La chaîne ne répond plus.",
  browserFormat: "Ce navigateur ne lit pas ce format.",
  frenchVersion: "Version française",
  unmuteTitle: "Activer le son ?",
  unmute: "Activer le son",
  mute: "Couper le son",
  language: "Langue",
  french: "Français",
  english: "Anglais",
  version: "Version",
  login: "Connexion",
  loginHint: "Accède à ton catalogue Minuit.",
  password: "Mot de passe",
  remember: "Se souvenir de moi",
  enter: "Entrer",
  signingIn: "Connexion…",
  loginFailed: "Connexion impossible",
  sessionExpired: "Session expirée — reconnecte-toi.",
  noAccount: "Pas de compte ?",
  trial: "Demander un essai 3 jours",
  devices: "Téléphone / tablette · Box & Smart TV Android",
  catalogDown: "Catalogue indisponible",
};

const en: typeof fr = {
  films: "Movies & Series",
  anime: "Anime",
  turkey: "Turkey",
  live: "Live TV",
  list: "My List",
  search: "Search",
  account: "Account & security",
  switchProfile: "Switch profile",
  logout: "Sign out",
  searchFilm: "A movie or a series",
  searchAnime: "An anime",
  searchLive: "A channel",
  searchTurkey: "A Turkish movie or series",
  searchHintTurkey: "Search for a Turkish title.",
  searchHintFilm: "Search for a movie or a series.",
  searchHintAnime: "Search for an anime.",
  searchHintLive: "Search for a channel.",
  searching: "Searching…",
  noResults: "No results.",
  searchFailed: "Search failed. Try again.",
  opening: "Opening…",
  notPlayable: "Not available to play yet",
  actors: "Cast",
  titles: "titles",
  movie: "MOVIE",
  show: "SERIES",
  play: "Play",
  playUnavailable: "Playback unavailable",
  episodes: "Episodes",
  close: "Close",
  sheetUnavailable: "Title unavailable",
  seasonUnavailable: "Season unavailable",
  episode: "Episode",
  playbackFailed: "Playback unavailable",
  channelDown: "The channel is not responding.",
  browserFormat: "This browser cannot play this format.",
  frenchVersion: "French version",
  unmuteTitle: "Turn sound on?",
  unmute: "Turn sound on",
  mute: "Mute",
  language: "Language",
  french: "French",
  english: "English",
  version: "Version",
  login: "Sign in",
  loginHint: "Open your Minuit catalog.",
  password: "Password",
  remember: "Remember me",
  enter: "Enter",
  signingIn: "Signing in…",
  loginFailed: "Could not sign in",
  sessionExpired: "Session expired — sign in again.",
  noAccount: "No account?",
  trial: "Request a 3-day trial",
  devices: "Phone / tablet · Android TV & boxes",
  catalogDown: "Catalog unavailable",
};

export type Copy = typeof fr;

export function copyFor(lang: SiteLang): Copy {
  return lang === "en" ? en : fr;
}
